# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-04 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0014_emailentry_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(max_length=255),
        ),
    ]
